### ISSUE TITLE
Discuss about the build process and general folder structure

### ISSUE THREAD

**Issue by pascal-zarrad** [Eukalyptus-Dreizack/deepcity-framework#22]
We should dicuss about the build process (Which tools to use, how should the compiled result look like -> bundled yes/no).
We also should define an initial structure for the source folders. 
This issue is accomplished when a strcuture is defined where the entry point of  a component and the location for tests is defined.

**Comment by pascal-zarrad** [comment]
We should definitly use gulp as task runner, as this enables a complex build sequence without too complex configuration.

**Comment by nicojust** [comment]
Gulp and TravisCI have been configured in #38
