### ISSUE TITLE
Add coding guidelines

### ISSUE THREAD

**Issue by pascal-zarrad** [Eukalyptus-Dreizack/deepcity-framework#24]
Coding guidelines should be added to keep a minimum quality standard. They should cover the overall structure of the project, the testing and code style.

**Comment by nicojust** [comment]
A draft has been created in the [Wiki](https://github.com/Eukalyptus-Dreizack/deepcity-framework/wiki/Guidelines)

**Comment by pascal-zarrad** [comment]
The guidelines have been accepted by @flaglias and me. They should be kept up-to-date when someone spots any missing or wrong guidelines in the current ones.
