### ISSUE TITLE
Setup Docker

### ISSUE THREAD

**Issue by pascal-zarrad** [Eukalyptus-Dreizack/deepcity-framework#35]
Setup Docker using docker-compose. For the start, it's enough to add NodeJS container. A database container and other stuff should be added when the feature that requires the container is being implemented.

**Comment by nicojust** [comment]
@pascal-zarrad What kind of database do we want to use?

**Comment by pascal-zarrad** [comment]
@nicojust I think we will deliver a MySQL container by default. But as we will use an ORM, if you have any suggestion for another DB we could also use that. As I think the best choice for a TypeScript ORM ist typesorm/typeorm, we would the following choices: MySQL, PostgreSQL, MariaDB, SQLite, MS SQL Server, Oracle, WebSQL

**Comment by nicojust** [comment]
> @nicojust I think we will deliver a MySQL container by default. But as we will use an ORM, if you have any suggestion for another DB we could also use that. As I think the best choice for a TypeScript ORM ist typesorm/typeorm, we would the following choices: MySQL, PostgreSQL, MariaDB, SQLite, MS SQL Server, Oracle, WebSQL

+1 for PostgreSQL

**Comment by pascal-zarrad** [comment]
+1 PostgreSQL

**Comment by nicojust** [comment]
As it stands right now we will postpone the implementation until we have skeleton or some such.
