### ISSUE TITLE
Plan all initial dependencies and add them

### ISSUE THREAD

**Issue by pascal-zarrad** [Eukalyptus-Dreizack/deepcity-framework#49]
**Is your feature request related to a problem? Please describe:**  
Yes, we need to define some dependencies on which the framework will be based and depend on.

**Describe the solution you'd like:**  
Discuss about the libraries and api's and fit our needs.
After everything has been defined, they should be required.

**Comment by pascal-zarrad** [comment]
We should use Discord.js as library to interact with the discord  api.

**Comment by nicojust** [comment]
We should use https://vuejs.org/ for the GUI

**Comment by nicojust** [comment]
We should use https://typeorm.io/ in combination with https://www.postgresql.org/

**Comment by pascal-zarrad** [comment]
> 
> 
> We should use https://vuejs.org/ for the GUI

We should add frontend dependencies right before we start to implement it to get the newest version of dependencies.

**Comment by pascal-zarrad** [comment]
We can use https://github.com/winstonjs/winston to implement logging

**Comment by pascal-zarrad** [comment]
Maybe add https://www.npmjs.com/package/rxjs to enable reactive programming

**Comment by nicojust** [comment]
Merged. As discussed vuejs comes later
